### PR TITLE
Fix crash when `share` is called from an iPad

### PR DESCRIPTION
**Pull request by neokree**
Applies the same fix used in `shareFile` method also for `share` method

This completely resolve the issue #8

### CODE REVIEW

**Comment by tedlasai** [comment]
I have the same problem and this would really help if the fix was added into the master branch!

**Comment by ludwiktrammer** [comment]
@lubritto Would you be able to merge this PR? Crashes for every single user using an iPad is a pretty severe issue.

**Comment by LiveRock** [comment]
The solution is the modify the SharePlugin.m file:

```
+ (void)share:(id)sharedItems withController:(UIViewController *)controller {
  UIActivityViewController *activityViewController =
      [[UIActivityViewController alloc] initWithActivityItems:@[ sharedItems ]
                                        applicationActivities:nil];

  // Original code
  //[controller presentViewController:activityViewController animated:YES completion:nil];

    //if iPhone
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone) {
        [controller presentViewController:activityViewController animated:YES completion:nil];
    }
    //if iPad
    else {
        // Change Rect to position Popover
        UIPopoverController *popup = [[UIPopoverController alloc] initWithContentViewController:activityViewController];
        [popup presentPopoverFromRect:CGRectMake(controller.view.frame.size.width/2, controller.view.frame.size.height/4, 0, 0)inView:controller.view permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
    }
}
```

**Comment by neokree** [comment]
@lubritto Could you please look at this MR? The problem is still there

**Comment by neokree** [comment]
@lubritto could you please look at this MR?

**Comment by neokree** [comment]
@lubritto could you please look at this MR?

**Review by lubritto — APPROVED** [review]
Thanks @neokree

**Pull request merged**
